name: layout_motion_example
description: Example app demonstrating layout_motion package.
publish_to: 'none'

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  layout_motion:
    path: ../
