name: layout_motion_example
description: Example app demonstrating layout_motion package.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  layout_motion:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
